import React from "react";
import { storiesOf } from "@storybook/react";
import { Button } from "@storybook/react/demo";
import {FormTitle} from '../components/FormTitle/FormTitle.story';
import {FormButtons} from '../components/Button/Button.story';
import {FormField} from '../components/FormField/FormField.story';
import {FormLine} from '../components/FormLine/FormLine.story';
import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import { Content } from "../components/content/Content.story";
import { SidebarMenu } from '../components/SidebarMenu/SidebarMenu.story';
import {LoginPage} from '../components/LoginPage/LoginPage.story';
import {Image} from '../components/LoginPageImage/LoginPageImage.story';