language: node_js
sudo: false
node_js:
  - 12.9.1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE annotatetheweb_db;'
install:
  - npm install
script:
  - npm run db:setup && npm run test
env:
  - DB_HOST="127.0.0.1"
    DB_PORT="3306"
    DB_NAME="annotatetheweb_db"
    DB_USER="root"
    DB_PASSWORD=""
    FIREBASE_API_KEY="AIzaSyAROMf-XVOoPXN_idZbYigkdn0eABbQbjA"
    FIREBASE_AUTH_DOMAIN="fp-annotatetheweb-class10.firebaseapp.com"
    FIREBASE_DATABASE_URL="https://fp-annotatetheweb-class10.firebaseio.com"
    FIREBASE_PROJECT_ID="fp-annotatetheweb-class10"
    FIREBASE_STORAGE_BUCKET="fp-annotatetheweb-class10.appspot.com"
    FIREBASE_MESSAGING_SENDER_ID="845246565627"
    FIREBASE_APP_ID="1:845246565627:web:714afab19ea6670695745e"
    FIREBASE_MEASUREMENT_ID="G-R64ZFS2G88"
